import { motion } from 'framer-motion'
import { TrendingUp, MessageCircle, BarChart3, AlertCircle } from 'lucide-react'
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card'
import { Button } from '../ui/Button'

const signals = [
    {
        ticker: 'NVDA',
        sentiment: 'Bullish',
        score: 94,
        mentions: '14.2k',
        insight: 'Unusual options activity detected alongside surging retail discussion regarding upcoming presentation.',
        color: 'text-green-400',
        bgColor: 'bg-green-400/10'
    },
    {
        ticker: 'TSLA',
        sentiment: 'Bearish',
        score: 32,
        mentions: '8.5k',
        insight: 'Negative sentiment spreading across forums ahead of delivery numbers. Watch support levels.',
        color: 'text-red-400',
        bgColor: 'bg-red-400/10'
    },
    {
        ticker: 'PLTR',
        sentiment: 'Neutral',
        score: 58,
        mentions: '4.1k',
        insight: 'Consistent accumulation pattern observed. Waiting for catalyst to break resistance.',
        color: 'text-yellow-400',
        bgColor: 'bg-yellow-400/10'
    }
]

export function Showcase() {
    return (
        <section className="py-24 bg-brand-bg relative overflow-hidden">
            <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-brand-primary/5 rounded-full blur-[100px] pointer-events-none" />

            <div className="container mx-auto px-4 relative z-10">
                <div className="flex flex-col md:flex-row justify-between items-end mb-12">
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        className="max-w-2xl"
                    >
                        <h2 className="text-3xl md:text-5xl font-mono font-bold mb-4">
                            Live <span className="text-gradient-primary">Signals</span>
                        </h2>
                        <p className="text-gray-400 text-lg">
                            A glimpse into the real-time insights generated by our AI engine.
                        </p>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        className="mt-6 md:mt-0"
                    >
                        <Button variant="outline" className="glass-panel text-white hover:border-brand-primary">
                            View All Tickers
                        </Button>
                    </motion.div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {signals.map((signal, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 30 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: index * 0.15 }}
                        >
                            <Card className="hover:border-brand-secondary/50 transition-colors h-full flex flex-col group relative overflow-hidden">
                                <div className={`absolute top-0 left-0 w-1 h-full ${signal.bgColor.replace('/10', '')}`} />

                                <CardHeader className="pl-8 pb-4">
                                    <div className="flex justify-between items-start">
                                        <div>
                                            <CardTitle className="text-3xl font-bold Tracking-wide">{signal.ticker}</CardTitle>
                                            <span className={`text-sm font-medium px-2 py-1 rounded-full ${signal.bgColor} ${signal.color} mt-2 inline-block`}>
                                                {signal.sentiment}
                                            </span>
                                        </div>
                                        <div className="text-right">
                                            <div className="text-2xl font-mono font-bold">{signal.score}/100</div>
                                            <div className="text-xs text-gray-500 uppercase tracking-wider">Conviction</div>
                                        </div>
                                    </div>
                                </CardHeader>

                                <CardContent className="pl-8 flex-grow">
                                    <div className="flex gap-4 mb-6">
                                        <div className="flex items-center text-gray-400 text-sm">
                                            <MessageCircle className="w-4 h-4 mr-1 text-brand-secondary" />
                                            {signal.mentions} mentions
                                        </div>
                                        <div className="flex items-center text-gray-400 text-sm">
                                            <TrendingUp className="w-4 h-4 mr-1 text-brand-primary" />
                                            Rising Velocity
                                        </div>
                                    </div>

                                    <div className="bg-black/40 p-4 rounded-lg border border-white/5 relative">
                                        <AlertCircle className="w-4 h-4 text-brand-primary absolute top-4 left-4" />
                                        <p className="text-sm text-gray-300 pl-6 leading-relaxed">
                                            "{signal.insight}"
                                        </p>
                                    </div>
                                </CardContent>
                            </Card>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    )
}
